---
ID: "d86f3fbb-96fa-5b1b-a0f2-4d19b963d2e9"
Parent: "14f7246e-b056-51c5-a78b-c862a8a29a05"
Template: "14f7246e-b056-51c5-a78b-c862a8a29a05"
Path: "/sitecore/templates/Project/contosoproject/Styleguide-FieldUsage-ItemLink/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230815T103554Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad61f6f4-b00b-4387-8a00-e8e8d5b8d2ea"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230815T103554Z
