---
ID: "eed2c5ed-ebe8-586d-81eb-0103c791e909"
Parent: "7601b9d5-f8b9-56ba-9e33-48a75a82d6d5"
Template: "7601b9d5-f8b9-56ba-9e33-48a75a82d6d5"
Path: "/sitecore/templates/Project/contosoproject/Styleguide-ComponentParams/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230815T103602Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fdee1c5e-37ad-421a-8dee-0102a090cdac"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230815T103602Z
